application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "pam"
  password: "pam"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "justin.parado@freelancer.com"
  authorization_token: "my-secret-token"
